// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $index from "./routes/index.tsx";
import * as $posts_uuid_ from "./routes/posts/[uuid].tsx";
import * as $posts_index from "./routes/posts/index.tsx";
import * as $users_handle_ from "./routes/users/[handle].ts";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/index.tsx": $index,
    "./routes/posts/[uuid].tsx": $posts_uuid_,
    "./routes/posts/index.tsx": $posts_index,
    "./routes/users/[handle].ts": $users_handle_,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
