export const tableStyle = {
  top: "─",
  topMid: "┬",
  topLeft: "╭",
  topRight: "╮",
  bottom: "─",
  bottomMid: "┴",
  bottomLeft: "╰",
  bottomRight: "╯",
  left: "│",
  leftMid: "├",
  mid: "─",
  midMid: "┼",
  right: "│",
  rightMid: "┤",
  middle: "│",
};
